version: 0.2

env:
  variables:
    SONARQUBE_HOST: http://18.185.105.214:9000/
  secrets-manager:
    SONARQUBE_TOKEN: tap/CICD/SonarQubeToken

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./mvnw install -Dmaven.test.skip=true
  post_build:
    commands:
      - ./mvnw test
      - ./mvnw sonar:sonar -Dsonar.host.url=$SONARQUBE_HOST -Dsonar.login=$SONARQUBE_TOKEN
artifacts:
  files:
    - target/app.jar
